const BASE_URL =
  process.env.NODE_ENV === 'production'
    ? 'https://gandan-news.vercel.app'
    : 'http://localhost:3000';

const env = {
  KAKAO_REST_API_KEY: process.env.NEXT_PUBLIC_KAKAO_REST_API_KEY,
  KAKAO_REDIRECT_URI: process.env.NEXT_PUBLIC_KAKAO_REDIRECT_URI,
  GOOGLE_CLIENT_ID: process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID,
  GOOGLE_REDIRECT_URI: process.env.NEXT_PUBLIC_GOOGLE_REDIRECT_URI,
  FIREBASE_DATABASE_URL: process.env.FIREBASE_DATABASE_URL,
  ACCESS_TOKEN_SECRET: process.env.ACCESS_TOKEN_SECRET,
  REFRESH_TOKEN_SECRET: process.env.REFRESH_TOKEN_SECRET,
  NAVER_NEWS_CLIENT_ID: process.env.NAVER_NEWS_CLIENT_ID,
  NAVER_NEWS_CLIENT_SECRET: process.env.NAVER_NEWS_CLIENT_SECRET,
  CRON_NEWS_TOKEN: process.env.CRON_NEWS_TOKEN,
  VAPID_PUBLIC_KEY: process.env.NEXT_PUBLIC_VAPID_PUBLIC_KEY,
  VAPID_PRIVATE_KEY: process.env.VAPID_PRIVATE_KEY,
  NOTIFICATION_SECRET: process.env.NOTIFICATION_SECRET,
  BASE_URL,
} as const;

export default env;
