name: test news

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *' # test

jobs:
  api-call:
    name: news api call
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Call Api
        id: post-news
        run: |
          curl --request POST \
          --url 'https://gandan-news.vercel.app/api/cron' \
          --header 'Authorization: ${{ secrets.CRON_NEWS_TOKEN }}')

      - name: Call Revalidate main
        id: revalidate-main
        run: |
          curl --request POST \
          --url 'https://gandan-news.vercel.app/api/revalidate?secret=${{ secrets.REVALIDATE_SECRET }}&url=/'
